services:
  client:
    build:
      context: ./client
    ports:
      - "5173:5173"

  wheel-of-life:
    build:
      context: ./server/wheel-of-life
    ports:
      - "8080:8080"
    depends_on:
      - genai

  genai:
    build:
      context: ./genai
    ports:
      - "5001:5001"
