apiVersion: v1
kind: Service
metadata:
  name: client
  namespace: "opsontherocks"
spec:
  type: {{ .Values.client.service.type }}
  selector:
    app: client
  ports:
    - port: {{ .Values.client.service.port }}
      targetPort: {{ .Values.client.service.targetPort }}
