apiVersion: apps/v1
kind: Deployment
metadata:
  name: genai
  namespace: "opsontherocks"
spec:
  replicas: {{ .Values.genai.replicaCount }}
  selector:
    matchLabels:
      app: genai
  template:
    metadata:
      labels:
        app: genai
    spec:
      containers:
        - name: genai
          image: "{{ .Values.genai.image.repository }}:{{ .Values.genai.image.tag }}"
          imagePullPolicy: {{ .Values.genai.image.pullPolicy }}
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          ports:
            - containerPort: {{ .Values.genai.service.targetPort }}
          env:
            {{- range .Values.genai.env }}
            - name: {{ .name }}
              {{- if .value }}
              value: "{{ .value }}"
              {{- else if .valueFrom }}
              valueFrom:
                {{- toYaml .valueFrom | nindent 16 }}
              {{- end }}
            {{- end }}
