{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opsontherocks-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    {{- $annotations := .Values.ingress.annotations | default dict }}
    {{- toYaml $annotations | nindent 4 }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - "{{ .Values.ingress.host }}"
      secretName: "{{ .Values.ingress.tlsSecret }}"
  {{- end }}
  rules:
    - host: "{{ .Values.ingress.host }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client
                port:
                  number: {{ .Values.client.service.port }}

          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: server-auth
                port:
                  number: {{ .Values.serverAuth.service.port }}

          - path: /wheel
            pathType: Prefix
            backend:
              service:
                name: server-wheel
                port:
                  number: {{ .Values.serverWheel.service.port }}

          - path: /genai
            pathType: Prefix
            backend:
              service:
                name: genai
                port:
                  number: {{ .Values.genai.service.port }}
{{- end }}
