{{- if .Values.ingress.enabled }}

{{/* CLIENT INGRESS */}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: client-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  tls:
    - hosts:
        - "client.54.166.45.176.nip.io"
      secretName: {{ .Values.ingress.tlsSecret }}
  rules:
    - host: "client.54.166.45.176.nip.io"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client
                port:
                  number: {{ .Values.client.service.port }}

---

{{/* AUTH INGRESS */}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  tls:
    - hosts:
        - "authentication.54.166.45.176.nip.io"
      secretName: {{ .Values.ingress.tlsSecret }}
  rules:
    - host: "authentication.54.166.45.176.nip.io"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: server-auth
                port:
                  number: {{ .Values.serverAuth.service.port }}

---

{{/* WHEEL INGRESS */}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wheel-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  tls:
    - hosts:
        - "wheel-of-life.54.166.45.176.nip.io"
      secretName: {{ .Values.ingress.tlsSecret }}
  rules:
    - host: "wheel-of-life.54.166.45.176.nip.io"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: server-wheel
                port:
                  number: {{ .Values.serverWheel.service.port }}

---

{{/* GENAI INGRESS */}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: genai-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  tls:
    - hosts:
        - "genai.54.166.45.176.nip.io"
      secretName: {{ .Values.ingress.tlsSecret }}
  rules:
    - host: "genai.54.166.45.176.nip.io"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: genai
                port:
                  number: {{ .Values.genai.service.port }}

{{- end }}
