apiVersion: v1
kind: Service
metadata:
  name: server-wheel
  namespace: "opsontherocks"
spec:
  type: {{ .Values.serverWheel.service.type }}
  selector:
    app: server-wheel
  ports:
    - port: {{ .Values.serverWheel.service.port }}
      targetPort: {{ .Values.serverWheel.service.targetPort }}
