apiVersion: v1
kind: Service
metadata:
  name: server-auth
  namespace: "ge96wac-opsontherocks"
spec:
  type: {{ .Values.serverAuth.service.type }}
  selector:
    app: server-auth
  ports:
    - port: {{ .Values.serverAuth.service.port }}
      targetPort: {{ .Values.serverAuth.service.targetPort }}
