global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'wheel-of-life'
    static_configs:
      - targets: ['wheel-of-life:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s

  - job_name: 'authentication'
    static_configs:
      - targets: ['authentication:8081']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s

  - job_name: 'genai'
    static_configs:
      - targets: ['genai:5001']
    metrics_path: '/metrics'
    scrape_interval: 10s 