
# Add TUM ID (used in Ingress host and namespace)
tumid: ge96wac

namespace:
  create: false

client:
  image:
    repository: ghcr.io/aet-devops25/team-opsontherocks/client
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 5173
    targetPort: 5173
  replicaCount: 1
  env:
    - name: VITE_SERVER_URL
      value: https://opsontherocks.student.k8s.aet.cit.tum.de
    - name: VITE_AUTH_URL
      value: https://opsontherocks.student.k8s.aet.cit.tum.de/auth
    - name: VITE_GENAI_URL
      value: https://opsontherocks.student.k8s.aet.cit.tum.de/genai

serverAuth:
  image:
    repository: ghcr.io/aet-devops25/team-opsontherocks/authentication
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8081
    targetPort: 8081
  replicaCount: 1
  env:
    - name: SPRING_DATASOURCE_URL
      value: jdbc:postgresql://postgres-postgresql:5432/wheelOfLifeDB
    - name: SPRING_DATASOURCE_USERNAME
      valueFrom:
        secretKeyRef:
          name: postgres-secret
          key: username
    - name: SPRING_DATASOURCE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgres-secret
          key: password
    - name: JWT_SECRET
      valueFrom:
        secretKeyRef:
          name: jwt-secret
          key: secret
    - name: SPRING_JPA_HIBERNATE_DDL_AUTO
      value: update
    - name: SPRING_JPA_SHOW_SQL
      value: "true"
    - name: CLIENT_ORIGIN
      value: https://opsontherocks.student.k8s.aet.cit.tum.de


serverWheel:
  image:
    repository: ghcr.io/aet-devops25/team-opsontherocks/wheel-of-life
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080
  replicaCount: 1
  env:
    - name: SPRING_DATASOURCE_URL
      value: jdbc:postgresql://postgres-postgresql:5432/wheelOfLifeDB
    - name: SPRING_DATASOURCE_USERNAME
      valueFrom:
        secretKeyRef:
          name: postgres-secret
          key: username
    - name: SPRING_DATASOURCE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgres-secret
          key: password
    - name: JWT_SECRET
      valueFrom:
        secretKeyRef:
          name: jwt-secret
          key: secret
    - name: SPRING_JPA_HIBERNATE_DDL_AUTO
      value: update
    - name: SPRING_JPA_SHOW_SQL
      value: "true"

genai:
  image:
    repository: ghcr.io/aet-devops25/team-opsontherocks/genai
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 5001
    targetPort: 5001
  replicaCount: 1
  env:
    - name: CLIENT_ORIGIN
      value: https://54.166.45.176
    - name: JWT_SECRET
      valueFrom:
        secretKeyRef:
          name: jwt-secret
          key: secret
    - name: OPENAI_API_KEY
      valueFrom:
        secretKeyRef:
          name: genai-secret
          key: OPENAI_API_KEY
    - name: OPENAI_API_BASE
      valueFrom:
        secretKeyRef:
          name: genai-secret
          key: OPENAI_API_BASE
    - name: OPENAI_MODEL
      valueFrom:
        secretKeyRef:
          name: genai-secret
          key: OPENAI_MODEL
    - name: DATABASE_URL
      value: postgresql://admin:admin@postgres:5432/wheelOfLifeDB

grafana:
  env:
    - name: GRAFANA_USER
      value: admin
    - name: GRAFANA_PASSWORD
      value: Vxk3ymezUnpvQqa3cHEVuXFBF7dmRMd2z1ZP8kP5bSs

ingress:
  enabled: true
  className: "nginx"
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  host: opsontherocks.student.k8s.aet.cit.tum.de
  tlsSecret: opsontherocks-tls
