name: Build Docker Images

on:
  push:

jobs:
  genai-test:
    name: GenAI Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: genai

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest
      - name: Run GenAI Test
        run: pytest test_genai.py

  wheeloflife-test:
    name: Wheel of Life Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server/wheel-of-life

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Run Wheel of Life Test
        run: ./gradlew test

  client-test:
    name: Client Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Run Client Tests
        run: npm test

  build:
    runs-on: ubuntu-latest
    env:
      #Should be read from GH vars instead, temporarily hardcoding it
      EC2_PUBLIC_IP: 54.166.45.176
    strategy:
      matrix:
        service: [ authentication, wheel-of-life, client, genai ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/${{ matrix.service }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch
            type=ref,event=pr

      - name: Build and push Docker image (backend)
        uses: docker/build-push-action@v5
        if: ${{ matrix.service != 'client' && matrix.service != 'genai' }}
        with:
          context: ./server/${{ matrix.service }}
          file: ./server/${{ matrix.service }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


      - name: Build and push Docker image (client/genai)
        if: ${{ matrix.service == 'client' || matrix.service == 'genai' }}
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
