name: Build Docker Images

on:
  push:
  workflow_dispatch: { }


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Should be read from GH vars instead, temporarily hardcoding
      EC2_PUBLIC_IP: 54.166.45.176
      RANCHER_BASE_URL: opsontherocks.student.k8s.aet.cit.tum.de
    strategy:
      matrix:
        service: [authentication, wheel-of-life, client, genai]
        target: [ec2, rancher]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/${{ matrix.service }}
          tags: |
            type=raw,value=latest-${{ matrix.target }},enable={{is_default_branch}}
            type=ref,event=branch
            type=ref,event=pr

      # Backend build
      - name: Build and push Docker image (backend)
        if: ${{ matrix.service != 'client' && matrix.service != 'genai' }}
        uses: docker/build-push-action@v5
        with:
          context: ./server/${{ matrix.service }}
          file: ./server/${{ matrix.service }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # Debug URLs
      - name: Debug URLs
        if: ${{ matrix.service == 'client' || matrix.service == 'genai' }}
        run: |
          echo "Target: ${{ matrix.target }}"
          echo "EC2_PUBLIC_IP = $EC2_PUBLIC_IP"
          echo "RANCHER_BASE_URL = $RANCHER_BASE_URL"
          if [ "${{ matrix.target }}" = "ec2" ]; then
            echo "VITE_SERVER_URL = https://wheel-of-life.${EC2_PUBLIC_IP}.nip.io"
            echo "VITE_AUTH_URL   = https://authentication.${EC2_PUBLIC_IP}.nip.io"
            echo "VITE_GENAI_URL  = https://genai.${EC2_PUBLIC_IP}.nip.io"
          else
            echo "VITE_SERVER_URL = https://${RANCHER_BASE_URL}/wheel"
            echo "VITE_AUTH_URL   = https://${RANCHER_BASE_URL}/auth"
            echo "VITE_GENAI_URL  = https://${RANCHER_BASE_URL}/genai"
          fi

      # Frontend build
      - name: Build and push Docker image (client/genai)
        if: ${{ matrix.service == 'client' || matrix.service == 'genai' }}
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VITE_SERVER_URL=${{ matrix.target == 'ec2' && format('https://wheel-of-life.{0}.nip.io', env.EC2_PUBLIC_IP) || format('https://{0}/wheel', env.RANCHER_BASE_URL) }}
            VITE_AUTH_URL=${{ matrix.target == 'ec2' && format('https://authentication.{0}.nip.io', env.EC2_PUBLIC_IP) || format('https://{0}/auth', env.RANCHER_BASE_URL) }}
            VITE_GENAI_URL=${{ matrix.target == 'ec2' && format('https://genai.{0}.nip.io', env.EC2_PUBLIC_IP) || format('https://{0}/genai', env.RANCHER_BASE_URL) }}
