name: Deploy Helm Chart to Rancher

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Debug cluster info (optional)
        run: |
          kubectl config get-contexts
          kubectl cluster-info

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/kubectl

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Ensure namespace exists
        run: kubectl get ns ge96wac-opsontherocks || kubectl create ns ge96wac-opsontherocks

      - name: Deploy using Helm
        run: |
          helm upgrade --install wheeloflife ./deployment/helm \
            --namespace ge96wac-opsontherocks --wait
